### ISSUE TITLE
DEV grunt, grunt build, npm install and npm test

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#125]
There are the commands

     grunt
     grunt build
     npm install
     npm test

Check the description of each of them. In particular how do I get the `demo.html` and the `Jasmine` page to be displayed. Sometimes the `demo.html` shows up, sometimes not.

**Comment by hhzl** [comment]
`npm install` comes first after the repository has been cloned.

It installs the necessary items into the `node_modules` directory.

This includes the local grunt.

**Comment by phyiction** [comment]
@phil4literacy `grunt build` generates the files in the `dist` directory. These JavaScript files are the  debug and minified versions of the LearnWords2 library. These files are copied to the `public/js` directory so the demo and Jasmine tests are using the "latest version" (i.e. derived from the JavaScript in `src`) of the library. 

The intention was that developers would run
`npm install`
`grunt`

Because of the watch task and livereload configuration any changes made to files in `src` would automatically rebuild the library and reload the demo and Jasmine tests web pages.

**Comment by hhzl** [comment]
README.md update

@phil4literacy , please recheck after #153 has been implemented.

**Comment by phil4literacy** [comment]
works as expected
