### ISSUE TITLE
file jasmine-app-bundle.js too long

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#42]
The file jasmine-app-bundle.js is so long that the failure messages you get in ``SpecRunner.html`` are difficult to interpret. The file has more than 1400 lines because other stuff is added.

**Comment by phyiction** [comment]
The debug parameter in browserify enables source maps. This means when you debug the spec you can put breakpoints in the original source files (orange directories) that were used to generate jasmine-app-bundle.js. It is longer because we include the [jasmine-expect](https://github.com/JamieMason/Jasmine-Matchers) library we implements many useful matchers that we could use for our tests. 

![specrunner](https://cloud.githubusercontent.com/assets/15158877/20458439/487794c4-ae73-11e6-8133-98f8b403bcfd.png)
