### ISSUE TITLE
Add usage instructions for module generated with browserify

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#96]

**Comment by phyiction** [comment]
Which file should these instructions be placed in?

**Comment by hhzl** [comment]
Preferably in [README.md](https://github.com/hhzl/LearnWords2/blob/master/README.md) if it is comparatively short. Otherwise in a new file in the `docs` folder.

**Comment by phyiction** [comment]
After further analysis the preferred approach is to have the application bundle the files in this library instead of generating a library (a JavaScript file) that the application would then include. It's essentially the work that I had to do to get the Jasmine test harness to work. I'll put a link in the README.md to a file in the docs directory.
